#!/usr/bin/python
from __future__ import print_function

import re
import sys

with open(sys.argv[1]) as f:
	commit_msg = f.read()
if not re.match('^(\d\d|all) - ', commit_msg):
	print("not accepted")
	print("commit title must start with the current experiment number")
	print("or 'all', followed by ' - '")
	print("regex used: /^(\\d\\d|all) - /")
	exit(1)
